name: Other
description: Use this for any other issues. Please do NOT create blank issues
body:
  - type: markdown
    attributes:
      value: |
        **Hey Luna Hacker !!!** 
        This is Lunahacks 2.0
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/grand-rick001/luna-hacks-projects/issues).
  - type: markdown
    attributes:
      value: "# Other issue"

  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)
          required: true